### ISSUE TITLE
Why AGPL?

### ISSUE THREAD

**Issue by zippy1981** [bilal-fazlani/tracker-enabled-dbcontext#53]
If this code is AGPL, that means that any code I link to it has to be GPL  or AGPL. Is it your intention that I cannot use this library with a closed source web app?

**Comment by bilal-fazlani** [comment]
I have no such intentions. Its just the lack of knowledge of licenses. 
I don't know which license should be used and what are its effects. 
now that you have raised an issue about it, let me ask you, 

I can see the GPL v2 is the most commonly used license on the internet and it has a new version v3. 
Should I change it to that ?

**Comment by zippy1981** [comment]
GPL has a similar issue. For a library like this, the best licenses would be LGPL (which would require changes people make to this library to be open source) or the MIT/BSD licenses which would give your users the most freedom, but not require them to make code available for changes they make to anyone.

**Comment by bilal-fazlani** [comment]
Alright,  I will go with LPGL. Thanks for your inputs Justin :)

**Comment by bilal-fazlani** [comment]
396481bf20185e770d46e98526fa89995fb9afff
07896793a5bff7a090962055ce372575003e110c

fixed issue

**Comment by trnelson** [comment]
Sorry to comment on a closed issue, but any GPL-based license makes it very difficult to use the software outside of open source projects. If that's your intention then of course it's totally fine, but your comment earlier seems to indicate that you weren't sure which to pick between MIT and LGPL, and the two are very, very different.

MIT license would mean I can use it freely in my software as long as I include a copy of the license; it's the best mix of ownership and freedom. LGPL means I need to make my entire project open source and available to anyone for 3 years, even though it's a proprietary, commercial software application. I was reviewing your project and it seemed like a perfect fit to use in an application I'm building for a client, however I'm unable to use it because that would force my client to make their entire application open source (which would get me fired and very likely sued).

If you're ever in doubt, and you just want to make your project available for people to use without forcing them to also make their projects open source, MIT is always the best choice.
