### ISSUE TITLE
Simple HistoryTable

### ISSUE THREAD

**Issue by smartmeter** [bilal-fazlani/tracker-enabled-dbcontext#73]
Hello, I found your nugget (sorry meant nuget :D ) , I am looking for a simple historytable for e.g. given a `BookTable` independent of the main table to track history `BookHistoryTable` where I can preform regular query operations.

I read the wiki, my questions are
1.   After I install EF, and your nuget, How can I configure EF to give me an autoHistoryTable
2.   Will I get an automatic model out of the DbContext Collection for the `BookHistoryTable` if I use your nuget
3. Can I perform CRUD operations besides the DbAudits, or will this mess it up?
4. How can I add custom columns, userId, Lat Long?
5. Are there any limitations on performance, or can I use this as any regular table

Appreciate any insight, this is exactly what I was looking for.  :+1:

**Comment by bilal-fazlani** [comment]
This library gives you a generic table where all logs are saved. You can rename that table to whatever you want but it will still be generic where all logs are saved. 

You can however make restrictions that you want to log only books. In that case the generic log table will have only book logs and you will lose logging for other tables. 

With version 3.5 however, I have exposed an event which gives you the generated log as an event argument. You can attach an event handler to that event and save the generated log anywhere you want.  In case you want individual log table for tables, you can create them yourself and using this event distribute the logs among those table. 
Take a look here. https://github.com/bilal-fazlani/tracker-enabled-dbcontext/wiki/Events

I personally wouldn't like the several log tables because of maintenance but its up to you really. 

Coming to your questions:,
1. After I install EF, and your nuget, How can I configure EF to give me an autoHistoryTable
You by default will get an auto history table once you install this. It will be a generic one (for all models, not just books). Just create a new migration and update database. you will see two new tables. I hope you are familiar with code first migrations.

2. Will I get an automatic model out of the DbContext Collection for the 2. Will I get an automatic model out of the DbContext Collection for the BookHistoryTable if I use your nuget if I use your nuget
No. Nothing specific for books. You will get a generic table where all logs will go. But as I said you can use the event to route the logs to anywhere you want. The only thing is you will have to write code to save them where ever you want. 

3. Can I perform CRUD operations besides the DbAudits, or will this mess it up?
Ofcourse, how else logs would generated if there are not CRUD operations. You can even perform CRUD operations on your logs. It won't break crash. But discuss with me what exactly you want. 

4. How can I add custom columns, userId, Lat Long?
hmmmmm, never really thought about it.

5. Are there any limitations on performance, or can I use this as any regular table.
It's a regular table. Only thing is will become huge with time depending on how much are you logging. So plan your strategy. may be move logs to archive after every month or so.


Feel free to ask more.

**Comment by patagoniahiker** [comment]
Thanks for taking the time to answer *(off topic: I am dazzled that Microsoft EF missed this functionality)*. After reading your answers I am seeing now that you were originally intending to solve a basic logging/audit of the DB table. However, I think you might be selling this short (a compliment) when I came across this little nugget, I found that/thought it could/has a broader capability :+1: 

I had originally envisioned your creation as turnkey audit table functionality, I saw that you had 3 scopes to configure this, global, table, column. Like in the case of the `BooksHistory` table, I was planning to turn it on just there.

If everything goes into one table, this could possibly expose changes to the password table etc right.

 6. What is the difference between the 2 versions, i.e. `tracker ASP identity` and `tracker regular`? If the project was using ASP identity, would that mean-- ASP Identity version would suffice and we get all the functionality there, or would I still need to add both nugets? I am sorry I am not clear here. Why exactly are there two and what does one buy me over the other?
 7.  I am testing your lib with a couple scenarios, **can you show me a snippet on how to have configure 1:1  & how would that configuration be different from 2:1 or 2:2 table tacker**, *source tables to: log/sink* table
 8.  Here what is telling Tracker, which tables, columns to save in a separate table location?      
 9.  
                using (var db = new TestTrackerContext())
                {
                    db.OnAuditLogGenerated += (sender, args) =>
                    {
                        var auditLog = args.Log;
    
                        DumpLogToAnotherDatabase(auditLog);
    
                    //skips saving to local database
                        args.SkipSaving = true;
                    };
                 }

 8. What would the performance hit be, how can I measure this.
 9. I did not see this, can you please expose and option to CRUD on the associated log table (similar to any Model)

**Comment by bilal-fazlani** [comment]
> 1) What is the difference between the 2 versions, i.e. tracker ASP identity and tracker regular? If the project was using ASP identity, would that mean-- ASP Identity version would suffice and we get all the functionality there, or would I still need to add both nugets? I am sorry I am not clear here. Why exactly are there two and what does one buy me over the other?

If you are using asp.net identity , install https://www.nuget.org/packages/TrackerEnabledDbContext.Identity. It will install its dependent packages.
If you are are not using asp.net identity, install https://www.nuget.org/packages/TrackerEnabledDbContext. TrackerIdentityContext class is available when you install the former package and it gives you ability to manage users and roles etc. Which is not available in the normal package. In other words, the former one is extension to Microsoft.AspNet.Identity.EntityFramework (read online about this) package and later is just an extension to EntityFramework package. 

> 2) I am testing your lib with a couple scenarios, can you show me a snippet on how to have configure 1:1 & how would that configuration be different from 2:1 or 2:2 table tacker, source tables to: log/sink table

Configurations would be normal. You would need foreign key properties for all navigation properties though. For example you have a `Car` class and it has an `Engine` property, make sure you also have `EngineId` property. That's it. 

> 3) Here what is telling Tracker, which tables, columns to save in a separate table location?

That logic is in `DumpLogToAnotherDatabase(auditLog)` method which is YOUR code and logic. I have just exposed an event handler so you can do whatever you want to do with that generated log. If you don't want to anything custom, log will automatically go to generic log table.

> 5) What would the performance hit be, how can I measure this.

Performance hit will be on saving, because on saving, it has to create and store a log. How you measure performance of application is not really in scope of this library. Googling  it might help I guess.

> 6) Once you inherit your dbContext class from `TrackerContext` (Or `TrackerIdentityContext` incase of identity), it will have `AuditLog` and `LogDetails` property. Via these properties, you have full access to logs just like any other domain model. you can do CRUD operations here. They are just another DbSets.

**Comment by patagoniahiker** [comment]
ok thanks. :+1:
