### ISSUE TITLE
The 'EventDateUTC' property on 'AuditLog' could not be set to a 'System.DateTimeOffset' value. You must set this property to a non-null value of type 'System.DateTime'.

### ISSUE THREAD

**Issue by flux88** [bilal-fazlani/tracker-enabled-dbcontext#82]
_context.GetLogs<Job>(GUID) returns this error.

This issue occured when I moved Entity Framework into a seperate project and deleted migrations and re-enabled. I can't figure out why this error as database hasn't changed except for migrations table.

Looking at the class structure and database table is there a problem here?

public class AuditLog
public DateTime EventDateUTC { get; set; }

Whilst database says:
EventDateUTC datatype:datetimeoffset (7)

**Comment by flux88** [comment]
Ok I deleted all tables in my database, and rebuilt as per instructions here: http://stackoverflow.com/questions/11679385/reset-entity-framework-migrations

Not sure why but it works now.

**Comment by bilal-fazlani** [comment]
The newer version of package has DateTime instead of DateTimeOffset. When you moved entity framework to a separate project, you installed latest version of this library and database got out of sync. Adding a migration and updating database should have solved the problem ideally. Anyways, the issues wasn't a bug in this library and its working now.
Hence closing this issue.

**Comment by flux88** [comment]
Thank you for your work Bilal. Very useful in my current project.
